# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-24 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beltexam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='taker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs_taken', to='beltexam.User'),
        ),
    ]
