# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-24 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltexam', '0006_auto_20181024_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='categories',
            field=models.BooleanField(default=True),
        ),
    ]
